hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchanged
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# Setting
mode: "test"
seed: 5
output_dir: ${hydra:run.dir}

# DataSet
data_path: "./data/data_test.csv"
ratio: [0.0, 0.0, 1.0]
t_len_in: 100
t_len_out: 50
num_conditions: 1

# Model
model: "Transolver"
MODEL:
  space_dim: 8 # 输入维数
  n_layers: 3   # network depth
  n_hidden: 128
  dropout: 0.15
  n_head: 8
  act: "gelu"
  mlp_ratio: 1
  fun_dim: 0 # 1 if use t
  out_dim: 2  # 输出维数
  slice_num: 16
  apply_kan: true
  kan_hidden_layer: [100, 32, 50]
  kan_grid_size: 16
  kan_gird_range: [-2, 0.5]
  t_len_out: 50


# Hyper-parameters
# train
epochs: 150
iters: 1000
batch_size: 256
lr: 0.0001
save_freq: 20
enable_ddp: false
resume_ep: -1
checkpoint: null

# eval(看是不是过拟合)
with_val: false
pred_ckpt: null

# test
